# -*- coding: utf-8 -*-
"""Clean_and_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-gV6aU6mdrUaFZV74Vuf7YBJY9j_89Vn
"""

import os, json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from itertools import combinations

# Upload the 3 CSVs (customers.csv, products.csv, orders.csv) when prompted.
# Skipped automatically if data/ already has them (e.g. after cloning the repo).
REQUIRED = ["customers.csv", "products.csv", "orders.csv"]
if not all(os.path.exists(f"data/{f}") for f in REQUIRED):
    from google.colab import files
    os.makedirs("data", exist_ok=True)
    for name in files.upload():
        os.replace(name, f"data/{name}")

def check(label, actual, expected):
    """Compare a computed value with the brief's expected value."""
    #print(f"   [{'PASS' if actual == expected else 'FAIL'}] {label}: got {actual} | expected {expected}")

# TASK 1: Load the three raw CSVs and show the orders shape before any cleaning
import pandas as pd
import numpy as np
from itertools import combinations

customers = pd.read_csv("data/customers.csv")
products  = pd.read_csv("data/products.csv")
orders    = pd.read_csv("data/orders.csv")

#print("customers shape:", customers.shape)   # (45, 6)
#print("products shape :", products.shape)    # (16, 4)
#print("orders shape   :", orders.shape)      # (180, 9)
#print(orders.head())

# TASK 2: Show the 7 raw payment_method values, then standardize with strip + upper
#print("Raw unique values :", orders["payment_method"].unique())
#print("Raw distinct count:", orders["payment_method"].nunique())     # 7

orders["payment_method"] = orders["payment_method"].str.strip().str.upper()

#print("\nCleaned unique values:", orders["payment_method"].unique())
#print("Cleaned distinct count:", orders["payment_method"].nunique()) # 3
#print("\nCounts after fix:")
#print(orders["payment_method"].value_counts())                       # CARD 70, UPI 55, COD 55

# TASK 3: Detect duplicates on the natural key (everything except order_id), keep first, drop the rest
natural_key = ["customer_id", "product_id", "order_date", "quantity",
               "discount_pct", "payment_method", "rating", "returned"]

dup_mask = orders.duplicated(subset=natural_key, keep="first")
dropped_rows = orders[dup_mask].copy()

#print("Duplicate rows flagged:", dup_mask.sum())                      # 5
#print("Dropped order_ids     :", dropped_rows["order_id"].tolist())   # O0176..O0180

orders_clean = orders[~dup_mask].copy()
#print("orders_clean shape    :", orders_clean.shape)                  # (175, 9)

# TASK 4: Impute on the deduplicated frame
# discount_pct: NaN -> 0 (no promo applied)
disc_missing = orders_clean["discount_pct"].isnull().sum()
#print("discount_pct rows affected:", disc_missing)                    # 12
orders_clean["discount_pct"] = orders_clean["discount_pct"].fillna(0)

# rating: NaN -> median of the non-null ratings (print the median BEFORE imputing)
rating_median = orders_clean["rating"].dropna().median()
rating_missing = orders_clean["rating"].isnull().sum()
#print("rating median (before imputing):", rating_median)             # 3.0
#print("rating rows affected           :", rating_missing)            # 15
orders_clean["rating"] = orders_clean["rating"].fillna(rating_median)

#print("\nNulls remaining:")
#print(orders_clean[["discount_pct", "rating"]].isnull().sum().to_dict())  # both 0

# TASK 5: Merge orders with products and customers, compute order_value, reconcile with Part 1 Report (a)
merged = (orders_clean
          .merge(products,  on="product_id",  how="left")
          .merge(customers, on="customer_id", how="left"))

merged["order_value"] = merged["quantity"] * merged["price"] * (1 - merged["discount_pct"] / 100)

cleaned_total = round(merged["order_value"].sum(), 2)
#print("Merged shape            :", merged.shape)
#print("Cleaned total revenue   : INR", f"{cleaned_total:,.2f}")      # 97358.30

# Independent check: order_value of the 5 dropped duplicate rows
dropped_val = dropped_rows.merge(products, on="product_id", how="left")
dropped_val["discount_pct"] = dropped_val["discount_pct"].fillna(0)
dropped_val["order_value"] = (dropped_val["quantity"] * dropped_val["price"]
                              * (1 - dropped_val["discount_pct"] / 100))
dropped_total = round(dropped_val["order_value"].sum(), 2)

# Raw total (Part 1 Report (a)): all 180 rows, NULL discount treated as 0
raw_all = orders.merge(products, on="product_id", how="left")
raw_all["order_value"] = (raw_all["quantity"] * raw_all["price"]
                          * (1 - raw_all["discount_pct"].fillna(0) / 100))
raw_total = round(raw_all["order_value"].sum(), 2)                   # 99860.20

delta = round(raw_total - cleaned_total, 2)                          # 2501.90

#print("Raw total (Part 1 (a))  : INR", f"{raw_total:,.2f}")
#print("Dropped 5 rows' value   : INR", f"{dropped_total:,.2f}")      # 2501.90
#print("Delta (raw - cleaned)   : INR", f"{delta:,.2f}")              # 2501.90

#print(f"""
RECONCILIATION NOTE
The cleaned total revenue of INR {cleaned_total:,.2f} is INR {delta:,.2f} lower than the raw Part 1 Report (a)
total of INR {raw_total:,.2f}. This entire difference is attributable to the 5 duplicate (double-submit) orders
{dropped_rows['order_id'].tolist()} removed in Task 3, whose combined order_value, summed independently, is
INR {dropped_total:,.2f}. The discount_pct and rating imputation does not contribute to the difference:
Part 1 already treated NULL discount as 0% via COALESCE, so filling those values with 0 leaves every
order_value unchanged, and rating is not used in any revenue calculation.
""")

# TASK 6: IQR method on quantity (flag outliers, do NOT drop them)
Q1 = merged["quantity"].quantile(0.25)
Q3 = merged["quantity"].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

#print(f"Q1={Q1}  Q3={Q3}  IQR={IQR}  lower={lower}  upper={upper}")  # 1.0 2.0 1.0 -0.5 3.5

merged["is_outlier"] = (merged["quantity"] < lower) | (merged["quantity"] > upper)

#print("\nOutlier rows:", merged["is_outlier"].sum())                  # 2
#print(merged.loc[merged["is_outlier"], ["order_id", "order_date", "quantity", "order_value"]])

# TASK 7: State the hypothesis, then test it with groupby
#print("HYPOTHESIS: Cash-on-Delivery (COD) orders have a higher return rate than Card or UPI orders.\n")

pay_stats = merged.groupby("payment_method")["returned"].agg(["count", "mean"])
pay_stats["return_rate_pct"] = (pay_stats["mean"] * 100).round(1)
#print(pay_stats)                                                      # CARD 14.7, COD 44.4, UPI 18.9

cod_rate = pay_stats.loc["COD", "return_rate_pct"]
other_max = pay_stats.drop("COD")["return_rate_pct"].max()
verdict = "Confirmed" if cod_rate > other_max else "Rejected"
#print(f"\nHypothesis verdict: {verdict} (COD {cod_rate}% vs next highest {other_max}%)")

# TASK 8: Return rate by payment_method x city_tier
seg = merged.groupby(["payment_method", "city_tier"])["returned"].agg(["count", "mean"])
seg["return_rate_pct"] = (seg["mean"] * 100).round(1)
#print(seg)

# Highest-risk segment
top_seg = seg["return_rate_pct"].idxmax()
top_seg_rate = seg.loc[top_seg, "return_rate_pct"]
top_seg_count = seg.loc[top_seg, "count"]
#print(f"\nHIGHEST-RISK SEGMENT: {top_seg[0]} + Tier-{top_seg[1]} cities at {top_seg_rate}% ({top_seg_count} orders)")

# Show that COD risk is not uniform across tiers
cod_t1 = seg.loc[("COD", 1)]
cod_t2 = seg.loc[("COD", 2)]
# print(f"COD Tier-1: {int(cod_t1['count'])} orders at {cod_t1['return_rate_pct']}%")   # 32 at 37.5
# print(f"COD Tier-2: {int(cod_t2['count'])} orders at {cod_t2['return_rate_pct']}%")   # 22 at 54.5
# print("COD risk is NOT uniform across tiers: a single blended COD rate hides the Tier-2 concentration.")

# TASK 9: Correlation matrix + strength band for each pair
corr_cols = ["rating", "returned", "discount_pct", "quantity"]
corr = merged[corr_cols].corr()
# print(corr.round(3))

def band(r):
    a = abs(r)
    if a < 0.2:  return "negligible"
    if a < 0.4:  return "weak"
    if a < 0.7:  return "moderate"
    return "strong"

# print("\nPairwise strength (0-0.19 negligible / 0.2-0.39 weak / 0.4-0.69 moderate / 0.7-1.0 strong):")
for a, b in combinations(corr_cols, 2):
    r = corr.loc[a, b]
    print(f"  {a:>13} vs {b:<13} r = {r:+.3f}  -> {band(r)}")

r_disc_ret = corr.loc["discount_pct", "returned"]
verdict = "Busted" if abs(r_disc_ret) < 0.2 else "Supported"
# print(f"\nHYPOTHESIS 'higher discounts reduce returns': {verdict} "
      f"(discount_pct vs returned r = {r_disc_ret:+.3f})")

# TASK 10: Monthly revenue with and without the two outlier orders
merged["order_date"] = pd.to_datetime(merged["order_date"])
merged["year_month"] = merged["order_date"].dt.to_period("M").astype(str)

# (1) Including outliers
monthly_all = merged.groupby("year_month")["order_value"].sum().round(2)

# (2) Excluding outliers (outlier-corrected)
monthly_corrected = merged[~merged["is_outlier"]].groupby("year_month")["order_value"].sum().round(2)

# print("(1) Monthly revenue INCLUDING outliers:")
# print(monthly_all.to_string())

# print("\n(2) Monthly revenue EXCLUDING outliers (corrected):")
# print(monthly_corrected.to_string())

apparent_peak = monthly_all.idxmax()
true_peak = monthly_corrected.idxmax()

# print(f"""
INTERPRETATION
{apparent_peak}'s apparent lead (INR {monthly_all[apparent_peak]:,.2f}) is an artifact of the two bulk orders that
landed in January: O0011 (quantity 25) on 2026-01-28 and O0098 (quantity 30) on 2026-01-10.
Once they are excluded, January falls to INR {monthly_corrected[apparent_peak]:,.2f} and {true_peak} is the
genuine peak month at INR {monthly_corrected[true_peak]:,.2f}.
Detecting the outliers (Task 6) BEFORE building the time series (Task 10) is what exposes this.
""")






